name: Development

services:
  server:
    image: codeberg.org/forgejo/forgejo:13
    container_name: forgejo
    user: ${uid}:${gid}
    environment:
      USER_UID: ${uid}
      USER_GID: ${gid}
      FORGEJO____APP_NAME: "Ulrichs Git"
      FORGEJO____RUN_USER: ${user}
    restart: unless-stopped
    volumes:
      - ./forgejo:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - '3000:3000'
      - '222:22'